name: 'Rust GitHub Action'
description: 'A GitHub Action written in Rust'
inputs:
  exclude:
    description: 'Comma-separated of paths to exclude from processing'
    required: false
    default: 'github/workspace/.git/,github/workspace/.fastembed_cache/'
outputs:
  data_path:
    description: 'The path for downloading artifact data'
runs:
  using: 'docker'
  image: 'Dockerfile'