name: 'Rust GitHub Action'
description: 'A GitHub Action written in Rust'
inputs:
  name:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  data_path:
    description: 'The path for downloading artifact data'
runs:
  using: 'docker'
  image: 'Dockerfile'