name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pguyot/arm-runner-action@v2

      - name: test action
        id: rust_action
        uses: ./
        with:
          name: 'Rust Developer'

      - name: log data_path
        run: echo "copy from ${{ steps.rust_action.outputs.data_path }}"

      - name: upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-artifact
          # path: ${{ steps.rust_action.outputs.data_path }}
          path: .artifact_data/*.json
          retention-days: 1
          include-hidden-files: true
          overwrite: true
          if-no-files-found: error