name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pguyot/arm-runner-action@v2

      - name: test action
        id: rust_action
        uses: ./
        with:
          name: 'Rust Developer'

      - name: consume output
        run: echo "The action took ${{ steps.rust_action.outputs.time }} to run"
